version: "3.8"

services:
  app:
    container_name: esoft-practice
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx knex migrate:latest --knexfile=src/knexfile.ts \
      && npx knex seed:run --knexfile=src/knexfile.ts \
      && npm run start"
    restart: always

  postgres:
    container_name: postgres_esoftPractice
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  pgdata: